dir: internal/mocks
pkgname: mocks
filename: mocks.go
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/kirillinakin/pingcast/internal/port:
    interfaces:
      APIKeyRepo: {}
      AlertEventPublisher: {}
      AlertEventSubscriber: {}
      AlertSender: {}
      ChannelRegistry: {}
      ChannelRepo: {}
      ChannelSenderFactory: {}
      CheckPublisher: {}
      CheckResultRepo: {}
      CheckerRegistry: {}
      DistributedMutex: {}
      FailedAlertRepo: {}
      HostLimiter: {}
      IncidentRepo: {}
      IncidentUpdateRepo: {}
      Metrics: {}
      MonitorEventPublisher: {}
      MonitorEventSubscriber: {}
      MonitorRepo: {}
      RateLimiter: {}
      SessionRepo: {}
      StatsRepo: {}
      TxManager: {}
      UptimeRepo: {}
      UserRepo: {}
